
FROM rust:1.91.1 AS builder

RUN <<EOF
apt update
apt install -y git ca-certificates git
EOF
COPY Cargo.lock /Cargo.lock
COPY Cargo.toml /Cargo.toml
COPY crates /crates
COPY examples /examples
COPY conformance /conformance

WORKDIR /examples/servers

RUN \
    --mount=type=cache,id=cargo,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    cargo fetch --locked
RUN --mount=type=cache,target=/app/target \
    --mount=type=cache,id=cargo,target=/usr/local/cargo/registry  \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    cargo build --example servers_counter_streamhttp  --release 

FROM debian:trixie
RUN <<EOF
apt update
apt upgrade -y
apt install -y python3
EOF

WORKDIR /
COPY --from=builder /target/release/examples/servers_counter_streamhttp /servers_counter_streamhttp
LABEL org.opencontainers.image.source=https://github.com/mcp-gateway-rs/mcp-gateway-rs
LABEL org.opencontainers.image.description="Mcp-Gateway-rs - open source highly experimental MCP Gateway in Rust."
ENV RUST_LOG=debug
ENTRYPOINT ["/servers_counter_streamhttp"]
